/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoexemploswing.telas;

import projetoexemploswing.DAO.AutorDao;
import projetoexemploswing.DAO.LivroDao;
import projetoexemploswing.Dominio.Autor;
import projetoexemploswing.Dominio.Livro;


public class FormPrincipal extends javax.swing.JFrame {

    public static LivroDao ld = new LivroDao();
    public static AutorDao ad = new AutorDao();
    
    public FormPrincipal() {
        initComponents();
        
        Livro livro1 = new Livro("Java","123qwe",new Autor("Enderson", "1346579-256"));
        Livro livro2 = new Livro("C++","123lwe",new Autor("Jacson", "15262579-256"));
        Livro livro3 = new Livro("C#","123jwe",new Autor("Lima", "96328.-256"));
        Livro livro4 = new Livro("JavaScript","123bwe",new Autor("Maia", "5423791-256"));
        
        Autor a1 = new Autor("Enderson", "1346579-256");
        Autor a2 = new Autor("Jacson", "15262579-256");
        
        ld.inserir(livro1);
        ld.inserir(livro2);
        ld.inserir(livro3);
        ld.inserir(livro4);
        ad.inserir(a1);
        ad.inserir(a2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuCadastroAutor = new javax.swing.JMenuItem();
        menuCadastroSair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Cadastro");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD1, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Livros");
        jMenuItem2.setToolTipText("");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        menuCadastroAutor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD2, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroAutor.setText("Autor");
        menuCadastroAutor.setToolTipText("");
        menuCadastroAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroAutorActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastroAutor);

        menuCadastroSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_END, java.awt.event.InputEvent.CTRL_MASK));
        menuCadastroSair.setBackground(new java.awt.Color(255, 255, 255));
        menuCadastroSair.setForeground(new java.awt.Color(255, 102, 102));
        menuCadastroSair.setText("Sair");
        menuCadastroSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuCadastroSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuCadastroSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FormListarLivors f1 = new FormListarLivors(this,false);
        f1.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuCadastroSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuCadastroSairActionPerformed

    private void menuCadastroAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroAutorActionPerformed
      FormAutor a1 = new FormAutor(this,false);
        a1.setVisible(true);
    }//GEN-LAST:event_menuCadastroAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem menuCadastroAutor;
    private javax.swing.JMenuItem menuCadastroSair;
    // End of variables declaration//GEN-END:variables
}
